dist: trusty

language: python

python:
    - '2.7'

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-numpy
      - python-vtk6
      - python-h5py

before_install:
  - pip install -U pytest pytest-cov

install:
  - pip install .

script:
  - cd test/ && pytest --cov meshio

after_success:
  - bash <(curl -s https://codecov.io/bash)
