sudo: true
dist: trusty

language: python

python:
    - '2.7'

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-add-repository -y ppa:nschloe/vtk-nightly
  - sudo apt-get update -qq
  - sudo apt-get -y install python-numpy python-vtk6
  - pip install -U pytest pytest-cov

install:
  - pip install .

script:
  - cd test/ && pytest --cov meshio

after_success:
  - bash <(curl -s https://codecov.io/bash)
