dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - python-h5py
      - python3-h5py
      - python-lxml
      - python3-lxml
      - python-numpy
      - python3-numpy
      - python-vtk6

before_install:
  - pip install -U pytest pytest-cov

install:
  - pip install .

script:
  - cd test/ && pytest --cov meshio

after_success:
  - bash <(curl -s https://codecov.io/bash)
