version: 2

jobs:

  build:
    working_directory: ~/meshio
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/vtk7
      - run: apt-get update
      - run: apt-get install -y git python3-h5py python3-netcdf4 python3-vtk7 python3-pip
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .[exodus,hdf5]
      # Make sure to get numpy 1.13.0
      - run: pip3 install -U numpy
      # make sure that rst converts correctly
      - run: apt install -y pandoc
      - run: pip3 install docutils pygments
      - run: make README.rst
      - run: python3 setup.py check -r -s
      # The actual test
      - run: pylint setup.py meshio/ test/*.py tools/meshio-convert
      - run: cd test/ && pytest --cov meshio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
