version: 2

jobs:

  python2:
    working_directory: ~/meshio
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python-h5py python-lxml python-numpy python-vtk6 python-pip
      - run: pip2 install -U pytest pytest-cov pylint
      - checkout
      - run: LANG=C.UTF-8 pip2 install .
      # The actual test
      - run: pylint meshio/
      - run: pylint test/*py
      - run: cd test/ && pytest --cov meshio

  python3:
    working_directory: ~/meshio
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/vtk7-nightly
      - run: apt-get update
      - run: apt-get install -y git python3-h5py python3-lxml python3-numpy python3-vtk7 python3-pip
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: LANG=C.UTF-8 pip3 install .
      # The actual test
      - run: pylint meshio/
      - run: pylint test/*py
      - run: cd test/ && pytest --cov meshio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-test:
    jobs:
      - python2
      - python3
