version: 2

jobs:
  build:
    working_directory: ~/meshio
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/vtk7-nightly
      - run: apt-get update
      - run: apt-get install -y git python3-h5py python3-lxml python3-numpy python3-vtk7 python3-pip
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install .
      # The actual test
      - run: cd test/ && pytest --cov meshio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
